@:jsRequire("koa-compose") extern class KoaCompose {
	@:overload(function<T1, U1, T2, U2, T3, U3>(middleware:ts.Tuple3<koa_compose.Middleware<koa.ParameterizedContext<T1, U1, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T2, U2, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T3, U3, Dynamic>>>):koa_compose.Middleware<koa.ParameterizedContext<Dynamic, Dynamic, Dynamic>> { })
	@:overload(function<T1, U1, T2, U2, T3, U3, T4, U4>(middleware:ts.Tuple4<koa_compose.Middleware<koa.ParameterizedContext<T1, U1, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T2, U2, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T3, U3, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T4, U4, Dynamic>>>):koa_compose.Middleware<koa.ParameterizedContext<Dynamic, Dynamic, Dynamic>> { })
	@:overload(function<T1, U1, T2, U2, T3, U3, T4, U4, T5, U5>(middleware:ts.Tuple5<koa_compose.Middleware<koa.ParameterizedContext<T1, U1, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T2, U2, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T3, U3, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T4, U4, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T5, U5, Dynamic>>>):koa_compose.Middleware<koa.ParameterizedContext<Dynamic, Dynamic, Dynamic>> { })
	@:overload(function<T1, U1, T2, U2, T3, U3, T4, U4, T5, U5, T6, U6>(middleware:ts.Tuple6<koa_compose.Middleware<koa.ParameterizedContext<T1, U1, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T2, U2, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T3, U3, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T4, U4, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T5, U5, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T6, U6, Dynamic>>>):koa_compose.Middleware<koa.ParameterizedContext<Dynamic, Dynamic, Dynamic>> { })
	@:overload(function<T1, U1, T2, U2, T3, U3, T4, U4, T5, U5, T6, U6, T7, U7>(middleware:ts.Tuple7<koa_compose.Middleware<koa.ParameterizedContext<T1, U1, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T2, U2, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T3, U3, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T4, U4, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T5, U5, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T6, U6, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T7, U7, Dynamic>>>):koa_compose.Middleware<koa.ParameterizedContext<Dynamic, Dynamic, Dynamic>> { })
	@:overload(function<T1, U1, T2, U2, T3, U3, T4, U4, T5, U5, T6, U6, T7, U7, T8, U8>(middleware:ts.Tuple8<koa_compose.Middleware<koa.ParameterizedContext<T1, U1, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T2, U2, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T3, U3, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T4, U4, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T5, U5, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T6, U6, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T7, U7, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T8, U8, Dynamic>>>):koa_compose.Middleware<koa.ParameterizedContext<Dynamic, Dynamic, Dynamic>> { })
	@:overload(function<T>(middleware:Array<koa_compose.Middleware<T>>):koa_compose.ComposedMiddleware<T> { })
	@:selfCall
	static function call<T1, U1, T2, U2>(middleware:ts.Tuple2<koa_compose.Middleware<koa.ParameterizedContext<T1, U1, Dynamic>>, koa_compose.Middleware<koa.ParameterizedContext<T2, U2, Dynamic>>>):koa_compose.Middleware<koa.ParameterizedContext<Dynamic, Dynamic, Dynamic>>;
}